{% set name = "hypothesis-graphql" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hypothesis_graphql-{{ version }}.tar.gz
  sha256: 468d45f7ab32c2f4121799b2aa5892bd7cd9c8231ec2059dd6b34ed4b976698c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.6,<4.0
  run:
    - graphql-core >=3.1.0,<3.3.0
    - hypothesis >=5.8.0,<7.0
    - python >=3.6,<4.0

test:
  source_files:
    - test
  imports:
    - hypothesis_graphql
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys test
  requires:
    - pip
    - pytest >=6.2.0,<8
    - pytest-xdist >=2.5,<3.0

about:
  home: https://github.com/Stranger6667/hypothesis-graphql
  summary: Hypothesis strategies for GraphQL queries and mutations
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
