{% set name = "hypothesis-graphql" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hypothesis-graphql-{{ version }}.tar.gz
  sha256: 3b3c242649f39d7d9bc00c548d8c6d4c592f86be95ad8bd1dc37e58a4f79cc06

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.6,<4.0
  run:
    - attrs >20.3.0,<=22.1.0
    - graphql-core >=3.1.0,<3.3.0
    - hypothesis >=5.8.0,<7.0
    - python >=3.6,<4.0

test:
  imports:
    - hypothesis_graphql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Stranger6667/hypothesis-graphql
  summary: Hypothesis strategies for GraphQL queries and mutations
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
